version: '3.8'

networks:
  pipelinex-net:
    name: pipelinex-tier-network
    driver: bridge

volumes:
  jenkins_home_dir:
    driver: local

services:
  # Jenkins Automation Server Engine Configuration
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: pipelinex-jenkins-master
    user: root
    ports:
      - "8081:8080" # Maps local port 8081 to Jenkins web UI to avoid conflicts
      - "50000:50000"
    environment:
      # Memory Constraint Control Optimization for 8GB Host Systems
      - JAVA_OPTS=-Xms512m -Xmx1024m -XX:+UseG1GC -Djenkins.install.runSetupWizard=false
    volumes:
      - jenkins_home_dir:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # Mounts Docker socket for Docker-in-Docker execution
    networks:
      - pipelinex-net
    deploy:
      resources:
        limits:
          memory: 1200M
    restart: unless-stopped